pipeline {
    parameters {
        choice(name: 'terraformAction', choices: ['apply', 'destroy'], description: 'Choose the Terraform action to perform')
    } 
    environment {
        aws_access-key     = credentials('aws_access-key')
        AWS_secrete_key = credentials('AWS_secrete_key')
    }

    agent any
    stages {
        stage('checkout') {
            steps {
                script {
                    dir("terraform") {
                        git branch: 'infra', url: 'https://github.com/Amith1777/complete-cicd-project-microdegree.git'
                    }
                }
            }
        }

        stage('Plan') {
            steps {
                sh 'pwd;cd eks/ ; terraform init'
                sh "pwd;cd eks/ ; terraform plan -out tfplan"
                sh 'pwd;cd eks/ ; terraform show -no-color tfplan > tfplan.txt'
            }
        }

        stage('Approval') {
            steps {
                script {
                    def plan = readFile 'eks/tfplan.txt'
                    input message: "Do you want to proceed with the Terraform action?",
                    parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
                }
            }
        }

        stage('Apply or Destroy') {
            when {
                expression {
                    return params.terraformAction == 'apply' || params.terraformAction == 'destroy'
                }
            }
            steps {
                script {
                    if (params.terraformAction == 'apply') {
                        sh "pwd;cd eks/ ; terraform apply -input=false tfplan"
                    } else if (params.terraformAction == 'destroy') {
                        sh "pwd;cd eks/ ; terraform destroy -auto-approve"
                    }
                }
            }
        }
    }
}
